---
- name: Delete managed files on the target user account's home drive # noqa: ignore-errors
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
    force: true
  loop: [.bash_profile, .bashrc, .editorconfig, .profile]
  ignore_errors: true
  tags: [clean]
- name: Delete managed dirs on the target user account's home drive # noqa: ignore-errors
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/{{ item }}"
    state: absent
    force: true
  loop:
    - .cache
  ignore_errors: true
  tags: [clean]
